### ISSUE TITLE
Library no longer compiles (abandoned?)

### ISSUE THREAD

**Issue by Smashcat** [claudeheintz/LXESP32DMX#32]
Examples no longer work with this library. Assume the ESP32 core has changed. Error is:

outputTest:61:3: error: 'esp_task_wdt_feed' was not declared in this scope
   esp_task_wdt_feed();
   ^~~~~~~~~~~~~~~~~

**Comment by claudeheintz** [comment]
the library has been updated so that the main branch compiles with boards manager esp32 v2.0.3
